server:
  port: 9000

spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:BankDbLocal
    username: sa
    password: sa

  logging:
    level:
      org.springframework.security: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://ep-small-dew-a2ocpyq8.eu-central-1.aws.neon.tech/BankDb
    username: BankDb_owner
    password: 8OkYEzPl3UQf
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: QA

  datasource:
    url: jdbc:postgresql://localhost:5432/BankInfoHolder
    username: postgres
    password: bank321

  jpa:
    generate-ddl: true
    show-sql: true