### GET request to example server
GET http://localhost:9000/customers

###
GET http://localhost:9000/customers
Accept: application/json

###

POST http://localhost:9000/customers
Content-Type: application/json

{
  "name": "SomeIa",
  "email": "johewwqn@gmail.com",
  "age": 90,
  "password": "1234321212",
  "phone": "+38054321607"
}

###

PUT http://localhost:9000/customers/1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "age": 12,
  "password": "1234",
  "phone": "+312231"
}

###

DELETE http://localhost:9000/customers/3
Accept: application/json

###

POST http://localhost:9000/customers/3/accounts?currency=USD


